export const LEGACY_RAILS_COMMIT =
  'f6f033a17bd4a4c600ffea8bc2e773d243f88f72' as const;
export const RAILS_SCHEMA_VERSION = '2024_04_10_210545' as const;

/**
 * Required columns from the audited Rails schema. Capture discovers and archives
 * all public tables/columns dynamically; this allowlist only makes known schema
 * regression fail closed.
 */
export const REQUIRED_RAILS_TABLES = {
  active_storage_attachments: [
    'id',
    'name',
    'record_type',
    'record_id',
    'blob_id',
    'created_at',
  ],
  active_storage_blobs: [
    'id',
    'key',
    'filename',
    'content_type',
    'metadata',
    'byte_size',
    'checksum',
    'created_at',
    'service_name',
  ],
  active_storage_variant_records: [
    'id',
    'blob_id',
    'variation_digest',
  ],
  communities: [
    'id',
    'name',
    'locale',
    'country',
    'created_at',
    'updated_at',
    'beta',
    'public',
    'slug',
    'description',
  ],
  curriculum_stories: [
    'id',
    'curriculum_id',
    'story_id',
    'created_at',
    'updated_at',
    'display_order',
  ],
  curriculums: [
    'id',
    'title',
    'description',
    'user_id',
    'created_at',
    'updated_at',
  ],
  flipper_features: [
    'id',
    'key',
    'description',
    'created_at',
    'updated_at',
  ],
  flipper_gates: [
    'id',
    'feature_key',
    'key',
    'value',
    'created_at',
    'updated_at',
  ],
  media: ['id', 'story_id', 'created_at', 'updated_at'],
  media_links: ['id', 'url', 'story_id', 'created_at', 'updated_at'],
  places: [
    'id',
    'name',
    'type_of_place',
    'created_at',
    'updated_at',
    'lat',
    'long',
    'region',
    'description',
    'community_id',
  ],
  places_stories: ['id', 'story_id', 'place_id'],
  speaker_stories: ['id', 'speaker_id', 'story_id'],
  speakers: [
    'id',
    'name',
    'created_at',
    'updated_at',
    'birthdate',
    'birthplace_id',
    'speaker_community',
    'community_id',
  ],
  stories: [
    'id',
    'title',
    'desc',
    'created_at',
    'updated_at',
    'permission_level',
    'date_interviewed',
    'language',
    'interview_location_id',
    'interviewer_id',
    'community_id',
    'topic',
  ],
  themes: [
    'id',
    'active',
    'created_at',
    'updated_at',
    'mapbox_style_url',
    'mapbox_access_token',
    'center_lat',
    'center_long',
    'sw_boundary_lat',
    'sw_boundary_long',
    'ne_boundary_lat',
    'ne_boundary_long',
    'zoom',
    'pitch',
    'bearing',
    'mapbox_3d',
    'map_projection',
    'community_id',
    'protomaps_api_key',
    'protomaps_basemap_style',
  ],
  users: [
    'id',
    'email',
    'encrypted_password',
    'reset_password_token',
    'reset_password_sent_at',
    'remember_created_at',
    'sign_in_count',
    'current_sign_in_at',
    'last_sign_in_at',
    'current_sign_in_ip',
    'last_sign_in_ip',
    'created_at',
    'updated_at',
    'role',
    'community_id',
    'super_admin',
    'username',
    'name',
  ],
} as const satisfies Record<string, readonly string[]>;

export type RequiredRailsTableName = keyof typeof REQUIRED_RAILS_TABLES;
