name: Claude Minimal Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Claude Review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          direct_prompt: |
            Follow-up Review for PR ${{ github.event.pull_request.number }}
            
            This PR implements authentication fields for Rails compatibility.
            
            Please review the recent changes and provide feedback on:
            - Code quality and security
            - Test coverage
            - Database migration correctness
            - Any remaining issues
            
            Focus on providing fresh insights since this is a follow-up review.
          use_sticky_comment: true